# challenge2_exceptions
Exception generated , Below is the attached screenshot of the same
#
Editing "ecause" statements makes it work correctly
#
<img width="959" alt="challenge2exceptions" src="https://github.com/vyomasystems-lab/riscv-ctb-challenge-GeekyDev2002DG/assets/72439194/2807ad0c-f87c-4fb1-bc0c-cea28ae6c422">
